### ISSUE TITLE
Litecoin deposit did not show up after 3days in the Atomex Windows wallet.

### ISSUE THREAD

**Issue by Tooniecoin** [atomex-me/atomex.client.core#21]
Sent to Atomex Sept 12/21
LP63ioktmZY5QtzLngNneSdkAdrMXZLjU3
https://explorer.viawallet.com/ltc/address/LP63ioktmZY5QtzLngNneSdkAdrMXZLjU3
Wallet is not reporting received and balance.

**Comment by matsakiv** [comment]
I apologize for the long answer! Most likely the problem was related to the data provider for Litecoin. We changed the data provider, so the problem is probably no longer relevant
