### ISSUE TITLE
Optimize updating balances for all currencies

### ISSUE THREAD

**Issue by isfriz** [atomex-me/atomex.client.core#31]
For some currencies such as USDT, updating balances is slow when there are a large number of transactions. It is necessary to remove unnecessary calls to the database and make the most of the information obtained earlier for optimization. In BTC replace the calculation of the balance for transits with requests to API.

**Comment by matsakiv** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Оптимизировать обновление балансов для всех валют](https://trello.com/c/nBKlxeVG/34-%D0%BE%D0%BF%D1%82%D0%B8%D0%BC%D0%B8%D0%B7%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D1%82%D1%8C-%D0%BE%D0%B1%D0%BD%D0%BE%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-%D0%B1%D0%B0%D0%BB%D0%B0%D0%BD%D1%81%D0%BE%D0%B2-%D0%B4%D0%BB%D1%8F-%D0%B2%D1%81%D0%B5%D1%85-%D0%B2%D0%B0%D0%BB%D1%8E%D1%82)
