### ISSUE TITLE
Switch to the new Gas / GasPrice model for Ethereum

### ISSUE THREAD

**Issue by isfriz** [atomex-me/atomex.client.core#32]

**Comment by matsakiv** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Перейти на новую модель Gas/GasPrice для Ethereum](https://trello.com/c/vCOGMIMK/133-%D0%BF%D0%B5%D1%80%D0%B5%D0%B9%D1%82%D0%B8-%D0%BD%D0%B0-%D0%BD%D0%BE%D0%B2%D1%83%D1%8E-%D0%BC%D0%BE%D0%B4%D0%B5%D0%BB%D1%8C-gas-gasprice-%D0%B4%D0%BB%D1%8F-ethereum)
