### ISSUE TITLE
What if I wanted to explore many addresses for other currencies like Tezos and Ethereum.

### ISSUE THREAD

**Issue by baahkusi** [atomex-me/atomex.client.core#61]
- My use case is that I have generated many addresses programatically using and I have a mnemonic.

- I use the addresses to receive payments. One address per payment.

- Using your wallet I can see it explores more paths for bitcion so I'm able to see all the addresses that have actually received paymen.t

- But for other currencies like Tezos and Ethereum, I am not able to see for all since it only explores the first two paths for them.

- Is there any settings I can use to modify the number of paths explored

- Or maybe if not could you point me to a part of the code where I can make such changes and use just for my use case.

Thanks.

**Comment by matsakiv** [comment]
At the moment there is no such setting in our UI. We are planning to redesign the algorithm for updating balances and addresses management.

You are right, now Atomex for Tezos and Ethereum scans in depth until it encounters N addresses without activity. You can change these parameters here:

[Tezos Internal chain depth](https://github.com/atomex-me/atomex.client.core/blob/e33311b74c7ffc3f0780e5f29f0ce32dc3389e8a/Atomex.Client.Core/Wallet/Tezos/TezosWalletScanner.cs#L18)
[Tezos External chain depth](https://github.com/atomex-me/atomex.client.core/blob/e33311b74c7ffc3f0780e5f29f0ce32dc3389e8a/Atomex.Client.Core/Wallet/Tezos/TezosWalletScanner.cs#L19)
[Ethereum Internal chain depth](https://github.com/atomex-me/atomex.client.core/blob/e33311b74c7ffc3f0780e5f29f0ce32dc3389e8a/Atomex.Client.Core/Wallet/Ethereum/EthereumWalletScanner.cs#L16)
[Ethereum External chain depth](https://github.com/atomex-me/atomex.client.core/blob/e33311b74c7ffc3f0780e5f29f0ce32dc3389e8a/Atomex.Client.Core/Wallet/Ethereum/EthereumWalletScanner.cs#L17)

I would not recommend increasing these parameters significantly. A large increase will slow down updating balances and may reach API limits. In your case it is optimal to increase these parameters one-time to find the necessary addresses. And after that  return the parameters to their original values.

**Comment by baahkusi** [comment]
This is great @matsakiv, thanks.
